Application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_5.urls'), name='schedule'),
    path('activity/', include('story_6.urls'), name='activity')
]

story_5/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<str:pk>', views.deleteItem, name='delete'),
    path('detail/<str:pk>', views.detail, name='detail')
]

story_6/urls.py
from django.urls import path

from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('delete/<str:pk>', views.delete, name='activityDelete'),
    path('delete/member/<str:pk>', views.deleteMember, name='memberDelete')
]

story_5/models.py
from django.db import models

# Create your models here.


class Course(models.Model):
    TERM_CHOICES = [
    ('Ganjil', 'Ganjil'),
    ('Genap', 'Genap')
    ]
    YEAR_CHOICES = [
    ('2019/2020', '2019/2020'),
    ('2020/2021', '2020/2021'),
    ('2021/2022', '2021/2022'),
    ('2022/2023', '2022/2023')
    ]
    name = models.CharField(max_length=50)
    teacher = models.CharField(max_length=100)
    sks = models.PositiveIntegerField()
    term = models.CharField(
        max_length=6, 
        choices= TERM_CHOICES,
        default= 'Ganjil')
    year = models.CharField(
        max_length=9,
        choices= YEAR_CHOICES,
        default='2019/2020'
    )
    room = models.CharField(max_length=20)
    desc = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class Assignment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateTimeField()
    name = models.CharField(max_length=100)
    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.name
    

story_6/models.py
from django.db import models

# Create your models here.

class Activity(models.Model):
    activity = models.CharField(max_length=100)
    def __str__(self):
        return self.activity

class Member(models.Model):
    member = models.CharField(max_length=100)
    aktivitas = models.ForeignKey(Activity, on_delete=models.CASCADE)
    def __str__(self):
        return self.member

story_5/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'teacher', 'sks', 'term', 'year', 'room', 'desc']
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
            'teacher' : forms.TextInput(attrs={'class': 'form-control'}),
            'sks' : forms.NumberInput(attrs={'class': 'form-control'}),
            'term' : forms.Select(attrs={'class': 'form-control'}),
            'year' : forms.Select(attrs={'class': 'form-control'}),
            'room' : forms.TextInput(attrs={'class': 'form-control'}),
            'desc' : forms.TextInput(attrs={'class': 'form-control'}),
        }

story_6/forms.py
from django import forms
from .models import Activity, Member

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "What do you want to do ?"}),
        }

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'member' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Wanna join ?"}),
        }

story_5/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Course, Assignment
from .forms import CourseForm
from datetime import datetime

# Create your views here.

def index(request):
    courses = Course.objects.all()
    context = {'courses': courses}
    return render(request, 'story_5/index.html', context)

def add(request):
    form = CourseForm()
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"Mata kuliah {request.POST['name']} berhasil ditambahkan!"))
            return redirect('add')
        else:
            messages.warning(request, ("Data yang anda masukkan tidak sesuai kriteria."))
            return redirect('add')
    context = {'form' : form}
    return render(request, 'story_5/add.html', context)

def deleteItem(request, pk):
    course = Course.objects.get(id=pk)
    course.delete()
    messages.success(request, (f"Mata Kuliah {course} berhasil dihapus"))
    return redirect('index')

def detail(request, pk):
    course = Course.objects.get(id=pk)
    assignment = Assignment.objects.filter(course = course)
    today = datetime.now().timestamp()
    passed = []
    nearDeadline = []
    farDeadline = []
    for item in assignment:
        if item.date.timestamp() < today:
            passed.append(item)
        elif item.date.timestamp() < today + 86400:
            nearDeadline.append(item)
        else:
            farDeadline.append(item)
    context = {
        'course': course, 
        'passed' : passed,
        'nearDeadline': nearDeadline,
        'farDeadline': farDeadline
        }
    return render(request, 'story_5/detail.html', context)

story_6/views.py
from django.shortcuts import render, redirect
from .models import Member, Activity
from .forms import MemberForm, ActivityForm
from django.contrib import messages


# Create your views here.

def activity(request):
    if request.method == "POST":
        formA = ActivityForm(request.POST)
        formB = MemberForm(request.POST)
        if formA.is_valid():
            formA.save()
            messages.success(request, (f"Kegiatan {request.POST['activity']} berhasil ditambahkan!"))
            return redirect('story_6:activity')
        elif formB.is_valid():
            formB.save()
            messages.success(request, (f"{request.POST['member']} berhasil bergabung!"))
            return redirect('story_6:activity')
        else:
            messages.warning(request, (f"Input tidak sesuai!"))
            return redirect('story_6:activity')
    else:
        formA = ActivityForm()
        formB = MemberForm()
        activities = Activity.objects.all()
        members = Member.objects.all()
        context = {
            'formA' : formA,
            'formB' : formB,
            'activities' : activities,
            'members' : members
        }
        return render(request, 'story_6/index.html', context)

def delete(request,pk):
    activity = Activity.objects.get(id=pk)
    activity.delete()
    messages.warning(request, (f"Kegiatan {activity} berhasil dihapus!"))
    return redirect('story_6:activity')

def deleteMember(request,pk):
    member = Member.objects.get(id=pk)
    member.delete()
    messages.warning(request, (f"{member} berhasil dihapus!"))
    return redirect('story_6:activity')

story_5/templates/story_5/add.html
{% extends 'story_5/base.html' %}
{% block content %}
{% include 'story_5/navbar.html' %}
<div class="container">
  {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    {% endif %}
    <form class="mt-5" method="POST">
      {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-5">
            <label>Nama Mata Kuliah</label>
            {{ form.name }}
          </div>
          <div class="form-group col-md-5">
            <label for="dosen">Dosen Pengajar</label>
            {{ form.teacher }}
          </div>
					<div class="form-group col-md-2">
            <label for="sks">Jumlah SKS</label>
            {{ form.sks }}
          </div>
        </div>
				<div class="form-row">
          <div class="form-group col-md-5">
            <label for="semester">Semester</label>
            {{ form.term }}
          </div>
          <div class="form-group col-md-5">
            <label for="tahunAjar">Tahun Ajar</label>
            {{ form.year }}
          </div>
          <div class="form-group col-md-2">
            <label for="ruang">Ruang</label>
            {{ form.room }}
          </div>
        </div>
				<div class="form-group">
					<label for="deskripsi">Deskripsi</label>
          {{ form.desc }}
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
      </form>
</div>
{% endblock content %}

story_5/templates/story_5/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Story 5 - Daftar Mata Kuliah</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

story_5/templates/story_5/detail.html
{% extends 'story_5/base.html' %}
{% block content %}
{% include 'story_5/navbar.html' %}
<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">{{ course.name }}</h1>
        <p class="lead">{{ course.term }} {{ course.year }}</p>
        <p>{{ course.desc }}</p>
        <hr class="my-4">
        <div class="row">
            <h4 class="col-10 col-md-auto">Ruang : <span class="badge badge-light">{{ course.room }}</span></h4>
            <h4 class="col-10 col-md-auto">Dosen : <span class="badge badge-light">{{ course.teacher }}</span></h4>
            <h4 class="col-10 col-md-auto">Jumlah SKS : <span class="badge badge-light">{{ course.sks }} SKS</span></h4>
        </div>
        <h4>Tugas :</h4>
        <ul class="list-group col-auto col-md-6">
            {% for item in nearDeadline %}
            <li class="list-group-item list-group-item-danger">
                <h5>{{ item.name }}</h5>
                <h6 class="text-secondary">{{ item.date }}</h6>
            </li> 
            {% endfor %}
            {% for item in farDeadline %}
            <li class="list-group-item list-group-item-success">
                <h5>{{ item.name }}</h5>
                <h6 class="text-secondary">{{ item.date }}</h6>
            </li> 
            {% endfor %}
            {% for item in passed %}
            <li class="list-group-item list-group-item-dark">
                <h5>{{ item.name }}</h5>
                <h6 class="text-secondary">{{ item.date }}</h6>
            </li> 
            {% endfor %}
          </ul>          
        <a class="btn btn-outline-dark mt-4" href="{% url 'index' %}" role="button">BACK</a>
    </div>
</div>
{% endblock content %}

story_5/templates/story_5/index.html
{% extends 'story_5/base.html' %}
{% block content %}
{% include 'story_5/navbar.html' %}
<div class="container my-4">
  {% if messages %}
	{% for message in messages %}
		<div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
			{{ message }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	{% endfor %}
	{% endif %}
  {% for course in courses %} 
    <div class="card mt-3">
      <div class="card-body d-flex justify-content-between flex-column flex-md-row">
          <div>
              <a href="{% url 'detail' course.id %}"><h5 class="card-title">{{ course.name }}</h5></a>
              <h6 class="card-subtitle mb-2 text-muted">{{ course.term }} {{ course.year }}</h6>
          </div>
          <a href="{% url 'delete' course.id %}" class="card-link text-danger mt-3 mt-md-0 mr-md-4 align-self-center">DELETE</a>
      </div>
    </div>
  {% endfor %}

</div>
{% endblock content %}

story_5/templates/story_5/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Mata Kuliah</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add' %}">Add</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story_6:activity' %}">My Activity</a>
        </li>

      </ul>
    </div>
  </div>
  </nav>

story_6/templates/story_6/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Story 6 - Daftar Kegiatan</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

story_6/templates/story_6/index.html
{% extends 'story_6/base.html' %}
{% block content %}
{% include 'story_6/navbar.html' %}
<div class="container py-4">
    <h1 class="display-4 text-center pb-4 border-bottom">My Activity</h1>
    <Form method="POST" class="row my-5">
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ formA.activity }}
        </div>
        <button type="submit" class="btn btn-dark col-2 mr-auto">Add Activity</button>
    </Form>
    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for activity in activities %}
        <div class="card bg-light mt-5" style="width: 18rem;">
            <div class="card-header">
                <div class="row">
                    <h5 class="col-10 mb-2">{{ activity }}</h5>
                    <a href="{% url 'story_6:activityDelete' activity.id %}" class="col-2">
                        <button type="button" class="close mb-2">&times;</button>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <h6 class="card-title">Members:</h6>
                <p></p>
                <ul>

                    {% for member in members %}
                    {% if member.aktivitas.id == activity.id %}
                    <li class="row">
                        <h5 class="col-10">{{ member }}</h5>
                        <a href="{% url 'story_6:memberDelete' member.id %}" class="col-2">
                            <button type="button" class="close">&times;</button>
                        </a>    
                    </li>
                    {% endif %}
                    {% endfor %}

                </ul>
                <form method="POST">
                    {% csrf_token %}
                    {{ formB.member }}
                    <input name="aktivitas" type="text" value="{{ activity.id }}" style="display: none;">
                    <button type="submit" class="btn btn-dark col-6 mt-2">Join</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

story_6/templates/story_6/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Mata Kuliah</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add' %}">Add</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'story_6:activity' %}">My Activity</a>
        </li>

      </ul>
    </div>
  </div>
  </nav>